// // This file is auto-generated by ./bin/rails stimulus:manifest:update
// // Run that command whenever you add a new controller or create them with
// // ./bin/rails generate stimulus controllerName

import { application } from "./application"

// Function to register controllers
const registerController = (name, controllerClass) => {
  return application.register(name, controllerClass)
}

registerController("hello", require("./hello_controller").default);
registerController("toggle_theme", require("../../components/shared/toggle_theme/component").default);
registerController("flash_message", require("../../components/shared/flash_message/component").default);
registerController("toggle_sidebar_btn", require("../../components/navbar/toggle_sidebar_btn/component").default);
